### ISSUE TITLE
rosdep keys unresolved

### ISSUE THREAD

**Issue by Dagrol** [mikepurvis/ros-install-osx#80] opened 2017-04-23 16:49 UTC
I am getting the following error when I run the script:

ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
python_qt_binding: No definition of [python-qt-bindings] for OS [osx]
rviz: No definition of [libqt4-opengl-dev] for OS [osx]
gl_dependency: No definition of [python-qt-bindings-gl] for OS [osx]
qt_gui_cpp: No definition of [qt4-qmake] for OS [osx]
qt_gui: No definition of [python-qt-bindings] for OS [osx]
turtlesim: No definition of [libqt4] for OS [osx]

I tried to clean my rosdep and updated it but still no luck. Any ideas ?

**Comment by mattcurf** [comment] 2017-04-27 04:12
I see the same errors above.  Mac OS X 10.12.4

**Comment by eaa3** [comment] 2017-05-16 00:00
I appear to be having the exact same issue (OSX 10.11.6 El captain):

`ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
python_qt_binding: No definition of [python-qt-bindings] for OS [osx]
rviz: No definition of [libqt4-opengl-dev] for OS [osx]
gl_dependency: No definition of [python-qt-bindings-gl] for OS [osx]
webkit_dependency: No definition of [python-qt-bindings-webkit] for OS [osx]
qt_gui_cpp: No definition of [qt4-qmake] for OS [osx]
qt_gui: No definition of [python-qt-bindings] for OS [osx]
turtlesim: No definition of [libqt4] for OS [osx]`

**Comment by ashwini** [comment] 2017-05-16 04:50
Same issue here, 10.12

**Comment by lujun723** [comment] 2017-05-24 03:22
Mark, Same issue, 10.12

**Comment by fitsir** [comment] 2017-05-24 13:51
Mark, same issue, 10.12.5

**Comment by ccckblaze** [comment] 2017-06-01 03:52
Mark, Same issue, 10.12

**Comment by ashishraste** [comment] 2017-06-17 15:50
Ran across the same issue, it has to do with Homebrew not supporting qt4 formula, as discussed here: https://github.com/ros/rosdistro/issues/14416

**Comment by mikepurvis** [comment] 2017-06-19 14:40
Yes, the issue is with Homebrew no longer having qt4. The only reasonable path forward here is to migrate this project to qt5/Kinetic, which I haven't had the time to do.

Going to close this ticket for now in favour of #63.

**Closed by mikepurvis** 2017-06-19 14:40 UTC
